name: Build

on:
  pull_request:
    branches: [main]

jobs:
  call-flutter_build:
    uses: Womotaq/github_actions/.github/workflows/flutter_build.yaml@v1.0.0
    secrets:
      FIREBASE_OPTIONS_DART: ${{ secrets.FIREBASE_OPTIONS_DART }}
