name: wo_form
description: "Easily create forms, and export/import them as json."
version: 1.2.1
repository: https://github.com/BudgetChess/wo_form
funding:
  - https://ko-fi.com/chresyr

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  cross_file: ^0.3.4+2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.4
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  phone_form_field: ^10.0.2
  popover: ^0.3.0+1

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.7.1
  test: ^1.25.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
