name: wo_form
description: "Easily create forms, and export/import them as json."
version: 1.4.0
repository: https://github.com/Womotaq/wo_form
funding:
  - https://ko-fi.com/chresyr

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  crop_your_image: ^2.0.0
  cross_file: ^0.3.4+2
  diacritic: ^0.1.6
  dotted_border: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_typeahead: ^5.2.0
  freezed_annotation: ^3.0.0
  http: ^1.4.0
  hydrated_bloc: ^10.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  phone_form_field: ^10.0.2
  popover: ^0.3.0+1
  rxdart: ^0.28.0
  universal_html: ^2.2.4

dependency_overrides:
  phone_form_field:
    git:
      url: git@github.com:Chresyr/phone_form_field.git
      ref: feat/tap-up-outside

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^3.0.0
  json_serializable: ^6.7.1
  test: ^1.25.2
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
